# Generated by Django 5.1.1 on 2024-12-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airlines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
